class FoodKeywords {
  static const foodKeywords = [
 'food', 'meal', 'diet', 'recipes', 'ingredients', 'nutrition','body','BMI','cook','cooking','cake'
  'cooking', 'cuisine', 'eating', 'dish', 'snack', 'breakfast',
  'lunch', 'dinner', 'healthy', 'unhealthy', 'eat', 'eating habits',
  'food groups', 'superfoods', 'organic', 'vegan', 'vegetarian',
  'gluten-free', 'dairy-free', 'nut allergies', 'portion control',
  'nutrients', 'calories', 'macros', 'micronutrients', 'vitamins',
  'minerals', 'dietary supplements', 'balanced diet', 'daily intake',
  'nutritional value', 'health benefits', 'weight management',
  'diet plan', 'nutritional requirements', 'food pyramid',
  'hydration', 'metabolism', 'protein', 'carbohydrates', 'fats',
  'fiber', 'sugar', 'healthy fats', 'trans fats', 'saturated fats',
  'cholesterol', 'organic foods', 'artificial sweeteners',
  'fasting', 'intermittent fasting', 'keto', 'paleo', 'Mediterranean diet',
  'low-carb', 'low-fat', 'low-calorie', 'whole grains', 'fruits', 'vegetables',
  'leafy greens', 'lean protein', 'portion sizes', 'meal prep', 'food safety',
  'organic farming', 'food security', 'sustainable food', 'food labels',
  'preservatives', 'additives', 'genetically modified organisms', 'GMOs',
  'foodborne illnesses', 'food poisoning', 'digestive health', 'gut health',
  'probiotics', 'prebiotics', 'food allergies', 'gluten sensitivity',
  'celiac disease', 'nutritional deficiencies', 'iron deficiency',
  'vitamin deficiency', 'calcium', 'magnesium', 'potassium', 'iron', 'zinc',
  'vitamin A', 'vitamin B', 'vitamin C', 'vitamin D', 'vitamin E', 'vitamin K',
  'antioxidants', 'phytonutrients', 'functional foods', 'mindful eating',
  'emotional eating', 'food cravings', 'hunger hormones', 'appetite regulation',
  'overeating', 'under-eating', 'eating disorders', 'anorexia', 'bulimia',
  'binge eating', 'orthorexia', 'food and mood', 'comfort food', 'stress eating',
  'mind-body connection', 'food psychology', 'social aspects of eating',
  'culinary arts', 'food preparation techniques', 'cooking methods',
  'food storage', 'fermented foods', 'pickling', 'canning', 'freezing',
  'healthy cooking oils', 'meal timing', 'portion distortion', 'food marketing',
  'food trends', 'fad diets', 'nutrition education', 'dietary guidelines',
  'food politics', 'food sustainability', 'food waste', 'food deserts',
  'local food movements', 'community-supported agriculture', 'farm-to-table',
  'food ethics', 'ethical eating', 'food sovereignty', 'food justice',
  'culinary tourism', 'food culture', 'regional cuisines', 'international cuisines',
  'food traditions', 'food rituals', 'culinary history', 'gastronomy',
   'organic farming', 'food security', 'sustainable food', 'food labels',
  'preservatives', 'additives', 'genetically modified organisms', 'GMOs',
  'foodborne illnesses', 'food poisoning', 'digestive health', 'gut health',
  'probiotics', 'prebiotics', 'food allergies', 'gluten sensitivity',
  'celiac disease', 'nutritional deficiencies', 'iron deficiency',
  'vitamin deficiency', 'calcium', 'magnesium', 'potassium', 'iron', 'zinc',
  'vitamin A', 'vitamin B', 'vitamin C', 'vitamin D', 'vitamin E', 'vitamin K',
  'antioxidants', 'phytonutrients', 'functional foods', 'mindful eating',
  'emotional eating', 'food cravings', 'hunger hormones', 'appetite regulation',
  'overeating', 'under-eating', 'eating disorders', 'anorexia', 'bulimia',
  'binge eating', 'orthorexia', 'food and mood', 'comfort food', 'stress eating',
  'mind-body connection', 'food psychology', 'social aspects of eating',
  'culinary arts', 'food preparation techniques', 'cooking methods',
  'food storage', 'fermented foods', 'pickling', 'canning', 'freezing',
  'healthy cooking oils', 'meal timing', 'portion distortion', 'food marketing',
  'food trends', 'fad diets', 'nutrition education', 'dietary guidelines',
  'food politics', 'food sustainability', 'food waste', 'food deserts',
  'local food movements', 'community-supported agriculture', 'farm-to-table',
  'food ethics', 'ethical eating', 'food sovereignty', 'food justice',
  'culinary tourism', 'food culture', 'regional cuisines', 'international cuisines',
  'food traditions', 'food rituals', 'culinary history', 'gastronomy',
  'nutritious', 'nutraceuticals', 'health foods', 'dietary habits', 'balanced eating',
  'functional medicine', 'integrative nutrition', 'meal plans', 'nutrient-dense',
  'mindful nutrition', 'healthy lifestyle', 'clean eating', 'whole foods',
  'plant-based', 'low-glycemic', 'glycemic index', 'anti-inflammatory diet',
  'heart-healthy', 'brain-healthy', 'gut-friendly', 'digestion', 'metabolic health',
  'blood sugar', 'cholesterol levels', 'blood pressure', 'weight loss', 'obesity',
  'diabetes', 'heart disease', 'cancer prevention', 'mental health', 'cognitive function',
  'immune system', 'anti-aging', 'energy levels', 'fitness nutrition', 'sports nutrition',
  'nutritional supplements', 'vitamin supplements', 'mineral supplements', 'herbal remedies',
  'dietary restrictions', 'special diets', 'food intolerance', 'allergen-free',
  'gluten-free diet', 'dairy-free diet', 'vegetarianism', 'veganism', 'pescetarianism',
  'flexitarian', 'ketogenic diet', 'paleo diet', 'Mediterranean diet', 'DASH diet',
  'mind diet', 'weight management', 'healthy cooking', 'meal prep', 'recipe ideas',
  'cooking inspiration', 'culinary creativity', 'healthy snacks', 'nutritious meals',
  'dietary fiber', 'protein sources', 'healthy fats', 'vitamin-rich foods',
  'mineral-rich foods', 'superfoods', 'functional ingredients', 'spices and herbs',
  'cooking oils', 'meal diversity', 'balanced nutrition', 'food and culture',
  'nutritional anthropology', 'traditional diets', 'global cuisines', 'ethnic foods','اوجبة'
   
  // Add more keywords as needed

];}
