// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5K36rgUSqXdYJjBTf9PzVF8NBZUbGnc',
    appId: '1:710289795645:web:575311fe7b52640b079854',
    messagingSenderId: '710289795645',
    projectId: 'mychatbot-c8443',
    authDomain: 'mychatbot-c8443.firebaseapp.com',
    storageBucket: 'mychatbot-c8443.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsui6G1rAEymC_E1VEvDr0CDp9Hn3IiSU',
    appId: '1:710289795645:android:9dea4c077a597f03079854',
    messagingSenderId: '710289795645',
    projectId: 'mychatbot-c8443',
    storageBucket: 'mychatbot-c8443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mndvcUgok3z7_w_styOe-frLTJdDD6Y',
    appId: '1:710289795645:ios:e32f15f694cfd2e6079854',
    messagingSenderId: '710289795645',
    projectId: 'mychatbot-c8443',
    storageBucket: 'mychatbot-c8443.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3mndvcUgok3z7_w_styOe-frLTJdDD6Y',
    appId: '1:710289795645:ios:247a13af4c87a867079854',
    messagingSenderId: '710289795645',
    projectId: 'mychatbot-c8443',
    storageBucket: 'mychatbot-c8443.appspot.com',
    iosBundleId: 'com.example.chatbot.RunnerTests',
  );
}
